name: push_to_docker_amd
on:
  workflow_dispatch:
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: 'Development'
    env:
      VERSION: '1.1.0'
      imageName: ${{ secrets.DOCKER_USERNAME }}/heimdall:$VERSION

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Java-21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'oracle'
          cache: 'maven'

      - name: Login to docker
        uses: docker/login-action@v3
        with:
          registry: 'docker.io'
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and publish image
        run: |
          ./mvnw spring-boot:build-image \
          -Dspring-boot.build-image.imageName=${{ env.imageName }} \
          -Dspring-boot.build-image.publish=true \
          -Dspring-boot.build-image.builder=paketobuildpacks/builder-jammy-base:latest